import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "it's okay to be not okay",
  description: "Generated by create next app",
};

//quiz json-data 필요
//trip openmap api 및 정보
//counsel 1대1 ai 상담기능?

export default function RootLayout({ children }) {

  return (
    <html lang="ko">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/">home</Link>
            </li>
            <li>
              <Link href="/quiz">quiz</Link>
            </li>
            <li>
              <Link href="/trip">trip</Link>
            </li>
            <li>
              <Link href="/counsel">counsel</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
