import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "it's okay to be not okay",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
    <html lang="ko">
      <body>
        <nav>
          <Link href="/">home</Link>
          <Link href='/about'>about</Link>
          <Link href="/trip">trip</Link>
          <Link href="/ost">ost</Link>
          <Link href="/counsel">counsel</Link>
        </nav>
        {children}

      </body>
    </html>
  );
}
